### ISSUE TITLE
how to install this lib?

### ISSUE THREAD

**Issue by fukemy** [SimformSolutionsPvtLtd/react-native-skia-catalog#44]
Hi, I am using this command ***npm i react-native-skia-catalog --force*** but got this error:
```
'react-native-skia-catalog@*' is not in this registry.
```

can u help?

**Comment by ravir-simform** [comment]
@fukemy We appreciate you giving this library a try. This is basically a catalog kind of thing to demonstrate the power of Skia library. It has not been published as npm package yet. We are planning to release it over npm as well and we are working on it. As of now if you want to use it, you can simply copy-paste code and do modifications according to your need.

**Comment by fukemy** [comment]
thanks you I got it
this lib is really helpful to me
