### ISSUE TITLE
really need your help about skia like

### ISSUE THREAD

**Issue by fukemy** [SimformSolutionsPvtLtd/react-native-skia-catalog#45]
Hi, first thanks for great library @ravir-simform.

I want to start show a skia-like with like state = true, but I dont know how to do it
I have tried to set 

```
const SkiaLike = ({
  size = 180,
  onChangeValue = () => {},
}: Partial<SkisLikeProps>): React.ReactElement => {
  const value = useValue<number>(1);
  const [isLike, setIsLike] = useState(true);
  const halfSize = size / 2;
 ...
```

 but it's not working to me, can u help? Thanks so much
 P/S: I just want so show red color heart immediately without animation on first time if user liked this message

**Comment by mukesh-simform** [comment]
We appreciate you bringing this to our attention. We would be happy to assist you in any way we can. Please take a look here(https://github.com/SimformSolutionsPvtLtd/react-native-skia-catalog/pull/46) and let me know if you have any further concerns. Thank you!

**Comment by fukemy** [comment]
thanks, I need modify a bit then work like charms!!!
```
<Paint opacity={isLike ? 1 : opacityHeart}>
        {/* <BlendColor color={heartColor} mode="srcIn" /> */}
        <BlendColor
          color={isLike ? Colors.red : heartColor}
          mode="srcIn"
        />
      </Paint>
```
